assignment4("test1.png", "gray", 0) 
assignment4("test1c.png", "color", 2)
assignment4("test2.png", "gray", 1)
assignment4("test2c.png", "color", 2)
assignment4("test3.png", "gray", 1)
assignment4("test3c.png", "color", 0) 
